=begin
#Site Manager API

#Site Manager API

The version of the OpenAPI document: 1.0.0
Contact: autosde@il.ibm.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/abstract_capability'
require 'openapi_client/models/account'
require 'openapi_client/models/account_post_request'
require 'openapi_client/models/account_post_response'
require 'openapi_client/models/address'
require 'openapi_client/models/address_create'
require 'openapi_client/models/auth_response'
require 'openapi_client/models/authentication'
require 'openapi_client/models/auto_sde_project'
require 'openapi_client/models/auto_sde_role'
require 'openapi_client/models/capability_translation'
require 'openapi_client/models/capability_translation_create'
require 'openapi_client/models/host'
require 'openapi_client/models/host_create'
require 'openapi_client/models/host_volume_connection'
require 'openapi_client/models/host_volume_connection_create'
require 'openapi_client/models/native_capability'
require 'openapi_client/models/profile'
require 'openapi_client/models/provisioning_strategy'
require 'openapi_client/models/service'
require 'openapi_client/models/service_abstract_capability_value'
require 'openapi_client/models/service_create'
require 'openapi_client/models/service_resource_attachment'
require 'openapi_client/models/storage_resource'
require 'openapi_client/models/storage_resource_create'
require 'openapi_client/models/storage_resource_response'
require 'openapi_client/models/storage_system'
require 'openapi_client/models/storage_system_create'
require 'openapi_client/models/system_type'
require 'openapi_client/models/system_type_create'
require 'openapi_client/models/volume'
require 'openapi_client/models/volume_create'
require 'openapi_client/models/volume_response'
require 'openapi_client/models/volume_safe_delete'
require 'openapi_client/models/volume_safe_delete_create'
require 'openapi_client/models/volume_update'

# APIs
require 'openapi_client/api/abstract_capability_api'
require 'openapi_client/api/account_api'
require 'openapi_client/api/address_api'
require 'openapi_client/api/authentication_api'
require 'openapi_client/api/auto_sde_project_api'
require 'openapi_client/api/auto_sde_role_api'
require 'openapi_client/api/capability_translation_api'
require 'openapi_client/api/host_api'
require 'openapi_client/api/host_volume_connection_api'
require 'openapi_client/api/native_capability_api'
require 'openapi_client/api/profile_api'
require 'openapi_client/api/provisioning_strategy_api'
require 'openapi_client/api/service_api'
require 'openapi_client/api/service_resource_attachment_api'
require 'openapi_client/api/storage_resource_api'
require 'openapi_client/api/storage_system_api'
require 'openapi_client/api/system_type_api'
require 'openapi_client/api/volume_api'
require 'openapi_client/api/volume_safe_delete_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
